### ISSUE TITLE
Error: Plugin lout missing dependency inert in connection: http://localhost:8080

### ISSUE THREAD

**Issue by doron2402** [hapijs/lout#121]
Hi,

I'm using hapi:9.0.2 and lout:7.0.0 and getting this error,

any idea before I dive inside of it?

**Comment by devinivy** [comment]
Yes– hapi v9 does not include `inert` (file handler plugin) automatically anymore.  You should register the `inert` module before registering `lout`, which depends on `inert`.  It's also suggested that you upgrade to a more recent version of hapi v9, since there were some kinks worked out with plugin dependency management.
